name: Build and Release FastGithub  
  
on:  
  push:  
    tags:  
      - 'v*'  
  workflow_dispatch:  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        runtime: [win-x64, linux-x64, osx-x64]  
      
    steps:  
    - uses: actions/checkout@v4  
      
    - name: Setup .NET  
      uses: actions/setup-dotnet@v4  
      with:  
        dotnet-version: '7.0.x'  
      
    - name: Restore dependencies  
      run: dotnet restore  
      
    - name: Build and Publish  
      run: |  
        dotnet publish FastGithub/FastGithub.csproj \  
          -c Release \  
          -r ${{ matrix.runtime }} \  
          --self-contained true \  
          -p:PublishSingleFile=true \  
          -p:PublishTrimmed=true \  
          -o ./publish/${{ matrix.runtime }}  
      
    - name: Create Archive  
      run: |  
        cd ./publish/${{ matrix.runtime }}  
        if [[ "${{ matrix.runtime }}" == "win-x64" ]]; then  
          zip -r ../../fastgithub-${{ matrix.runtime }}.zip .  
        else  
          tar -czf ../../fastgithub-${{ matrix.runtime }}.tar.gz .  
        fi  
      
    - name: Upload Artifacts  
      uses: actions/upload-artifact@v4  
      with:  
        name: fastgithub-${{ matrix.runtime }}  
        path: |  
          fastgithub-${{ matrix.runtime }}.*
