name: Build FastGithub  
  
on:  
  push:  
    branches: [ main, master ]  
  pull_request:  
    branches: [ main, master ]  
  release:  
    types: [ published ]  
  
jobs:  
  build:  
    runs-on: windows-latest  
      
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v4  
        
    - name: Setup .NET  
      uses: actions/setup-dotnet@v4  
      with:  
        dotnet-version: |  
          8.0.x  
            
    - name: Restore dependencies  
      run: dotnet restore FastGithub.sln  
        
    - name: Build solution  
      run: dotnet build FastGithub.sln --configuration Release --no-restore  
        
    - name: Publish FastGithub  
      run: |  
        dotnet publish FastGithub/FastGithub.csproj -c Release -o ./publish/fastgithub --self-contained true -r win-x64 -p:PublishSingleFile=true  
        dotnet publish FastGithub/FastGithub.csproj -c Release -o ./publish/fastgithub-linux --self-contained true -r linux-x64 -p:PublishSingleFile=true  
        dotnet publish FastGithub/FastGithub.csproj -c Release -o ./publish/fastgithub-osx --self-contained true -r osx-x64 -p:PublishSingleFile=true  
          
    - name: Build UI (Windows only)  
      run: |  
        msbuild FastGithub.UI/FastGithub.UI.csproj /p:Configuration=Release /p:Platform="Any CPU"  
          
    - name: Upload artifacts  
      uses: actions/upload-artifact@v4  
      with:  
        name: fastgithub-all-platforms  
        path: |  
          ./publish/  
          FastGithub.UI/bin/Release/
