name: Build FastGithub  
  
on:  
  push:  
    branches: [ main, master ]  
  pull_request:  
    branches: [ main, master ]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
      
    steps:  
    - uses: actions/checkout@v4  
      
    - name: Setup .NET  
      uses: actions/setup-dotnet@v4  
      with:  
        dotnet-version: '7.0.x'  
      
    - name: Restore dependencies  
      run: dotnet restore FastGithub.sln  
      
    - name: Build  
      run: dotnet build FastGithub.sln --no-restore --configuration Release --verbosity quiet
      
    - name: Test  
      run: dotnet test FastGithub.sln --no-build --configuration Release --verbosity normal  
  
  build-multi-platform:  
    runs-on: ${{ matrix.os }}  
    strategy:  
      matrix:  
        os: [ubuntu-latest, windows-latest, macos-latest]  
          
    steps:  
    - uses: actions/checkout@v4  
      
    - name: Setup .NET  
      uses: actions/setup-dotnet@v4  
      with:  
        dotnet-version: '7.0.x'  
      
    - name: Build for ${{ matrix.os }}  
      run: |  
        dotnet restore FastGithub.sln  
        dotnet build FastGithub.sln --configuration Release --verbosity quiet
          
    - name: Publish artifacts  
      run: |  
        dotnet publish FastGithub/FastGithub.csproj -c Release -o ./publish/${{ matrix.os }}  
          
    - name: Upload artifacts  
      uses: actions/upload-artifact@v4  
      with:  
        name: fastgithub-${{ matrix.os }}  
        path: ./publish/${{ matrix.os }}
